services:
  postgresql:
    image: postgres:17.4-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=app-db
      - POSTGRES_USER=user-db
      - POSTGRES_PASSWORD=app_1234

    ports:
      - 5432:5432